@startuml
'https://plantuml.com/class-diagram
!theme spacelab

class Ventilation {}

class MVHR {}

class TemperatureSensor{}

class Device{}

class Store{}

class VentilationConfig

VentilationConfig "1"-- "1" Store
Ventilation "1"--VentilationConfig
Device <|-- MVHR
Device <|-- TemperatureSensor
Ventilation "1"--"1..n" Device

@enduml